name: Generate

on: [push]

permissions: read-all

jobs:
  generate:
    runs-on: Ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v3
      with:
          path: main
    - name: Checkout Json Branch
      uses: actions/checkout@v3
      with:
          path: json
    - name: Checkout Licenses Repo
      uses: actions/checkout@v3
      with:
        repository: github/choosealicense.com
        path: choosealicense-com
    - name: Install Dependencies
      run: npm install
      working-directory: main/
    - name: Create Empty File
      run: touch licenses.json
      working-directory: main/
    - name: Generate Json
      run: npm run generate
      working-directory: main/
    - name: Move Json File
      run: mv main/licenses.json json/
    - name: Config Git User
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions"
      working-directory: json/
    - name: Commit Json File
      run: |
        git pull
        git add .
        git commit -m "Update licenses.json"
        git push origin json
      working-directory: json/
        
